- data/services.json
Change the Support link to the github page https://github.com/TissUUmaps/TissUUmaps and use the biif email (biif@scilifelab.se) instead of Carolina's email for a contact for support
> Update TissUUmap service

- content/services/_index.md
- data/services.json
- layouts/services/list.html
Chores:
- Jira issue: FREYA-280
- added service status link in description
- added service status icon with link in each service card
> added status link to check service status

- data/data_sources.json
In this patch I have added a new key "disease_types" (type string[]) to all data sources. Currently, only data sources related to .ddls = "Precision Medicine and Diagnostics" have values, all others are added as empty arrays.
These were added as a custom tag that we want to use for filters on the Precision Medicine Portal, with @natashiab (Natashia Benzian Olsson) selecting the tags.
I have tested the new JSON in our application and it seems to be working correctly as far as I can tell.
> Adding disease_types to data_sources.json

- layouts/funding_calls/list.html
- layouts/partials/header.html
When a `deadline_time` is added to a funding call, it will also be displayed with the date. For example, it would look like
> Show funding deadline time when available

- .github/workflows/dockerhub.yml
- .github/workflows/link-checker.yml
- .github/workflows/pa11y_test.yaml
- .github/workflows/trivy-branch.yaml
- .github/workflows/trivy-scheduled.yaml
Currently we are using `checkout` version 3, it uses an older version of `node 16.x`
There is new newer version 4 for `checkout`, which uses `node 20.x`
> Version bump: Git action 'checkout'

- Dockerfiles/Dockerfile
Currently, `data.scilifelab.se` can be used in a `iframe` in any sites.
The added `ngnix` configuration will prevent it from being rendered in any `iframe` in any site.
> Prevent from being iframed

- .github/workflows/dockerhub.yml
- .github/workflows/link-checker.yml
- .github/workflows/trivy-branch.yaml
- .github/workflows/trivy-scheduled.yaml
Github decides to use node v20 for actions from December 2024, so action methods using older version of node displays warnings about this.
In this PR the relevant methods are updated to use the latest versions. Already [done in portal](https://github.com/ScilifelabDataCentre/pathogens-portal/pull/1194), all looks good.
> Bump action methods version

- Dockerfiles/Dockerfile
We are trying to show a `pdf` file in an embed frame, so change allow to be frame in the `SAMEORIGIN` i.e. our own site
> Allow frame for same origin

- .github/workflows/trivy-branch.yaml
- .github/workflows/trivy-scheduled.yaml
`trivy` workflow fails randomly due to too many request error. Trivy knows this and currently trying to fix it, as a work around they have also hosted their DB file in ECR. So adding the ecr repo via ENV variable `TRIVY_DB_REPOSITORY`  should reduce the problem if not fixing it.
> Trivy workaround

- static/css/styles.css
This will fix the extra white space created in the search results while highlighting the typed text in the title.
> Remove padding on result text highlight

- content/resources/storage.md
This pull request includes a small update to the `content/resources/storage.md` file. The change updates the URL for the KTH Royal Institute of Technology (KTH) resource link to a new address.
Closes: [FREYA-1249](https://scilifelab.atlassian.net/browse/FREYA-1249)
> Updates old link of KTH storage with new one

- layouts/partials/head.html
- layouts/partials/schema.html
This pull request introduces the addition of Schema.org structured data to the website, which will help improve SEO and provide better data to search engines. The changes include modifications to the `layouts/partials/head.html` and the creation of a new partial, `schema.html`, which generates the appropriate schema based on the type of page being viewed.
Closes [FREYA-663](https://scilifelab.atlassian.net/browse/FREYA-663)
> Adds Schema.org Structured data for improved SEO

- .github/CODEOWNERS
- Open Science own their content (markdown, images, data files) on this site.
The purpose is to auto-select the right group of people for code reviews (i.e. not have Freya be reviewers, unless requested, on the content files for Open Science). I'd suggest that in the start someone from Freya would be a reviewer but that would be just at the start.
> FREYA-1235: Add OpenScience GitHub team as codeowners of their content

- content/open_science/resources.md
- Site broadly uses URLs of this form and using the Hugo shortcode caused issues in the Docker build
> Change link from Resources to Glossary

- layouts/partials/header.html
`Hugo` have introduced `Ancestors` variable to get all the parents of a page, that can be used for `breadcrumbs`.
Current implementation is limited to only three levels of depth.
Suggested by @aishling-scilifelab in [FREYA-1309](https://scilifelab.atlassian.net/jira/software/projects/FREYA/boards/17?jql=assignee%20%3D%205e7c3fd02e3fce0c33deaed8&selectedIssue=FREYA-1309).
> Make use of hugo ancestors for breadcrumbs

- Dockerfiles/Dockerfile
- content/sv/_index.md
- layouts/partials/toc.html
Updating `hugo` version to the latest, and made some tweaks as there a `warn` message (see below).
```
WARN deprecated: lang in front matter was deprecated in Hugo v0.144.0 and will be removed in a future release.
```
> Update hugo version

- .github/pull_request_template.md
This PR adds a pull request template to provide guidelines and improve uniformity of our PRs.
- Add `pull_request_template.md` in `.github/`
I'm not sure this can be tested by creating a new PR as it is not in the default branch yet.
But it will look exactly like this description with placeholders instead of the PR specific text.
Closes: [FREYA-914](https://scilifelab.atlassian.net/browse/FREYA-914)
> FREYA-914: Add pull request template

- .github/.gitmessage.txt
- README.md
This PR introduces a `.gitmessage.txt` file that provides a standardized, lightweight conventional commit template for contributors to follow while working on feature branches.
The goal is to improve commit consistency across the team and support our evolving Git workflow, which includes structured squash commits for merging into develop.
After pulling this change, contributors can configure Git to use this commit message template by running the following command in the root of the repo:
`git config --local commit.template .github/.gitmessage.txt`
This will cause Git to pre-fill your commit message editor with the template whenever you run:
`git commit`
✅ Tip: Use this during development to follow our lightweight conventional commit structure.
> Freya-1342: Add git commit message template

- .github/.markdownlint-cli2.yaml
- content/open_science/_index.md
- content/open_science/glossary.md
- content/open_science/initiatives/_index.md
- content/open_science/initiatives/collaborative.md
- content/open_science/initiatives/our_initiatives.md
- content/open_science/initiatives/scilifelab.md
- content/open_science/open_science_stories.md
- content/open_science/resources.md
- content/open_science/who_we_are.md
This PR fixes markdownlint errors in Open Science content to align with formatting standards. As part of PR #383 ([FREYA-1232](https://scilifelab.atlassian.net/browse/FREYA-1232))
- Removed trailing spaces and added final newlines
-  Updated Config file (.github/.markdownlint-cli2.yaml) to 
- Allow multiple H1 (  MD025 set to false)
- Allow internal links (  MD051 set to false)
- Allow lines up to 180 characters, to fit links and longer titles
For Freya: Check if you agree with the updates to the config file. 
For the open science team: To comply with hyperlink formatting I had to rephrase, so you mainly need to check if commit https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/407/commits/a7cb5daf47b7ea3ba125bdb4e2d0d4f98fd5d502 looks good.
> FREYA-1232 Open Science Linting: Fix markdownlint errors in Open Science content

- content/open_science/who_we_are.md
This PR fixes incorrect captions on the Who We Are page.
Would be great to include this in the upcoming release (#410). It might also introduce additional conflicts to those resolved in #411
Open Science team added to confirm the captions are now correct
Team FREYA added as reviewers to confirm merging into develop won't cause issues with their pending changes
> Update mixed up captions on who we are page

- content/news/2025-05-14.md
- content/news/2025-05-15.md
- content/news/2025-05-20.md
- content/open_science/activities.md
- content/open_science/contact_us.md
- data/open_science/events.json
- layouts/shortcodes/update_activities.html
This PR creates a new page in Open Science section to show events and announcements
- Added new `activities.md` content file
- Added new `shortcode` to handle dynamic stuff
- Added new front matter parameter on open science news items
- Added new `JSON` file for external events
- Populated `JSON` file  for external events
- Added captions for each section in the open science activities section 
Closes: [FREYA-1230](https://scilifelab.atlassian.net/browse/FREYA-1230)
> FREYA - 1230: Add events and announcements page for Open Science

- schemas/data/open_science/collaborative_initiatives.schema.json
- schemas/data/open_science/events.schema.json
- schemas/data/open_science/glossary.schema.json
- schemas/data/open_science/initiatives.schema.json
- schemas/data/open_science/team.schema.json
This PR adds schema to validate `data/open_science` json files
- Add 5 new schema files in `schema/data/open_Science`
Closes: [FREYA-1459](https://scilifelab.atlassian.net/browse/FREYA-1459)
> FREYA-1459: Add schema for open science data

- data/data_sources.json
- schemas/data/data_sources.schema.json
The precision medicine portal used the `disease_type` in the `data_sources.json` file, so putting it back
- put back `disease_type` in the `data_sources.json` file
This is to undo something done in previous PR, so no existing jira issue
> Put back disease_type in data sources
