config.yaml
This sort of link works in covid portal - may only work for new pages in data portal
=> correct image link for twitter

content/funding/20220608.md, content/funding/20220617.md, content/funding/20220617a.md, content/funding/20220617b.md, content/funding/20220617c.md, content/funding/20220617d.md, content/funding/20220617e.md, content/funding/20220617f.md, content/funding/20220617g.md, content/funding/20220617h.md, content/funding/20220617i.md, content/funding/_index.md, content/news/2022-06-17.md, layouts/funding/list.html, layouts/partials/header.html, layouts/partials/navbar.html
Includes all current opportunties, a layout template for the items there (needs cleaning up when possible). Changes to navbar to make font smaller. Want to add a form at a later date
=> Funding page initiated

content/funding/20220621.md, content/funding/20220621a.md, content/news/2022-06-21.md
add news item about the latest DH and the most recent two jobs
=> Add news item about DH and jobs

content/calls_and_jobs/20220628b.md, content/calls_and_jobs/20220628c.md
Adding latest two NBIS positions
=> add 2 NBIS positions

content/highlights/unravelling_mitoribosome_assembly.md
A. Amunts got in touch to inform us of data release. Updated data highlight accordingly
=> Update link following data release

content/news/2022-09-29.md, data/services.json
Need to merge this as an example to develop first, then let RDM guidelines team see it. Once confirmed - live on Wednesday last thing
=> Add RDM portal as a service

layouts/index.html
* Move "see all ..." to top of each section
* Display only 6 services at homepage
=> Homepage updates

layouts/index.html, static/css/styles.css
* Collapse button for long descriptions of serve apps
* Have "new" tag for latest news updates for a week
* Figshare link updated to new one
=> Homepage related modifications

data/events.json
to reflect latest updates to information for this latest event
=> Update DC/NBIS event for 13th December

content/events/_index.md, content/funding_calls/_index.md, content/jobs/_index.md, data/funding_calls.json, layouts/funding_calls/list.html, layouts/jobs/list.html
Add funding calls page following funding and jobs split
=> Funding calls

content/news/2023-01-20a.md, content/news/2023-01-20b.md, data/jobs.json
=> Add news related to new features/additions

layouts/partials/footer.html, layouts/partials/head.html
Since it is update within v5, no further tweaks were needed
=> Update bootstrap 5.0.1 to 5.2.3

data/services.json, layouts/services/list.html
Have text search feature to filter services based on keywords.
=> Search feature for services

content/services/e-infrastructure.md
Prevent text looking too dense
=> minor change to AIDA layout

data/events.json, data/jobs.json
Added jobs available in week 23 plus an event advertised
=> Added jobs and an event

data/events.json, data/funding_calls.json, data/jobs.json
Adding latest jobs, calls, and events. Should do one more update before the summer.
=> events, jobs, funding for week 25

layouts/jobs/list.html
Instead of having the jobs in `/data` folder, we now try to have it in bloserver
https://blobserver.dc.scilifelab.se/blob/data_platform_jobs.json/info
=> Fetch jobs from blobserver instead of data folder

layouts/funding_calls/list.html
=> Enable dynamic updating for funding opportunities on the platform

content/news/2023-09-28.md, content/resources/altmetrics.md, data/services.json, layouts/partials/header.html
Finishing touches to the resource on alternative metrics. Can now go live.
=> Finalising altmetrics resource following comments

content/services/_index.md, layouts/events/list.html, layouts/jobs/list.html, layouts/services/list.html, static/css/styles.css
In service page the services are split into tabs (for researchers and facility). Also made the filter options to look similar in all the pages they exist.
P.S: Though it looks big, the changes in the `css` file is just re-arrangements.
=> Services page with new look

layouts/index.html
Serve now in production, so can use new API
=> update serve api

layouts/contact/list.html, layouts/events/list.html, layouts/funding_calls/list.html, layouts/highlights/list.html, layouts/index.html, layouts/jobs/list.html, layouts/partials/header.html, layouts/resources/list.html, layouts/services/list.html, static/css/styles.css
This PR contains my latest updates in the ongoing accessibility improvements
=> Accessibility improvements - form labels, contrast updates etc

Dockerfiles/Dockerfile
Using only official linux and webserver images
=> Use only official images

layouts/highlights/list.html
It was missing parenthesis causing the function to fail.
=> DH Search bug fix

layouts/index.html, layouts/partials/header.html
Making a possibility to have dynamic banner that can be defined in blob server.
=> Add dynamic banners

layouts/index.html, static/css/styles.css
There some minor accessibility issues at homepage, this PR fixes it.
=> Homepage accessibility fixes

content/highlights/immunofluorescence.md, content/highlights/multiomics_analysis_all_cancer.md, content/privacy/_index.md, content/resources/altmetrics.md, content/resources/e-infrastructure.md, content/resources/storage.md, content/services/subcellbarcode.md, layouts/_default/baseof.html, layouts/highlights/single.html, layouts/index.html, layouts/news/list.html, layouts/partials/navbar.html, layouts/services/list.html, static/css/styles.css
These are accessibility issues reported by pa11y. These are not raised by wave, none of this have any affect visually or functionally, but it is a better change code wise.
Issued addressed:
* Duplicate id in same page
* Missing `alt` tags
* Missing title for iframes
=> Fix accessibility reported by pa11y

.github/pa11y.config, .github/sitemap.xml, .github/workflows/pa11y_test.yaml
Setting up a (scheduled) workflow to run `pa11ly` to automatically check for accessibility issues.
=> Setup pa11y accessibility check

layouts/events/list.html, layouts/index.html
A new blob file is created for all events, it will have a field called `target` which will be used to display the event in the right website
=> Fetch events from new file

.github/CODEOWNERS
- Team Freya were already owners.
=> FREYA-1149: Add CODEOWNERS file

layouts/partials/footer.html
We need to add that the website content in licensed under CC-BY 4.0
While at it done some code cleanup.
=> Add CC-BY 4 license to footer

assets/css/styles.css, assets/js/search.js, layouts/search/list.html
As mentioned in [FREYA-1239](https://scilifelab.atlassian.net/jira/software/projects/FREYA/boards/17?assignee=5e7c3fd02e3fce0c33deaed8&selectedIssue=FREYA-1239), there was a minor contrast error. So have made the text colour slightly darker.
=> Fix search text colour

CONTRIBUTING.md
The information in `CONTRIBUTING.md` for adding/updating events is outdated, this PR will change it to current way of doing this.
=> Update contribute doc for events

assets/css/styles.css, layouts/events/list.html, layouts/jobs/list.html
This pull request includes changes to enhance the user experience of filtering functionality for events and job listings. The most important changes include adding accordion-style filters and improving the styling for better user experience for both small and large screens.
Closes: [FREYA-579](https://scilifelab.atlassian.net/browse/FREYA-579)
=> Improves user experience of side-bars filters on both large and small screens

data/open_science/team.json
Small correction of a job title: "Project Coordinator (Open Source Software and AI ~~communities~~)" in data/open_science/team.json
=> Update job title: removed "communities" from Alma Nilsson's title

assets/css/styles.css, layouts/open_science/list.html, layouts/open_science/single.html, layouts/partials/open_science_page.html, layouts/partials/sidebar.html
* Fixes active link to highlighted
* Have new partial and use them in `list.html` and `single.html` as they are same
* Remove `min-height` for the side bar as it creates extra space on bigger screens
=> OS sidebar and layout fix

content/open_science/_index.md, content/open_science/glossary.md, content/open_science/who_we_are.md
This PR aims at coordinating the new Open Science section release on data platform.
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/380 
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/381
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/385 
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/386
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/387 
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/391
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/392
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/393
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/394
- https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/395
- …
=> FREYA-1308: Open Science section release coordination

content/open_science/_index.md, content/open_science/glossary.md, content/open_science/initiatives/_index.md, content/open_science/initiatives/collaborative.md, content/open_science/initiatives/our_initiatives.md, content/open_science/initiatives/scilifelab.md, content/open_science/open_science_stories.md, content/open_science/resources.md, content/open_science/who_we_are.md, data/open_science/collaborative_initiatives.json, layouts/open_science/list.html, layouts/open_science/single.html, layouts/shortcodes/image_text_row.html
This PR changes the formatting (only frontend) on the pages, specifically it
* adds space between sections
* introduces top level headers on all pages
* adds banners to our initiatives 
Moreover it adds EOSC to the collaborative initiatives, and links the checklists and adds graphics credits
=> Open science formatting updates

data/open_science/collaborative_initiatives.json, data/open_science/initiatives.json
This PR fixes the broken links on the initiatives page cards, whose paths were not updated after file names were changed.
- Paths updated in `data/open_science/collaborative_initiatives.json` and `data/open_science/initiatives.json`.
=> Open Science: Update initiatives urls with new filenames

.gitignore, package.json, pnpm-lock.yaml, schemas/data/resources.schema.json, scripts/test-json-schemas.js
This pull request introduces JSON schema validation for resource files and updates dependencies to support the validation process. Key changes include adding new dependencies, creating a JSON schema for resource files, and implementing a script to validate JSON files against their schemas.
- **JSON Schema Validation:**
-- `schemas/data/resources.schema.json`: Added a new schema to validate resource objects in the Data Centre portal. The schema defines required fields, their types, and constraints such as string patterns and enumerations.
-- `scripts/test-json-schemas.js`: Implemented a script to recursively validate JSON files in the `data` directory against their corresponding schemas. The script uses `ajv` for validation and provides detailed results and a summary of the validation …
=> Freya-1398 & Freya-1464: Setup and initiate JSON-Schema testing
